Jane Downer<br>
A20452471<br>
CS 577 - 02<br>
Fall 2022<br>

# Homework 0

In [1]:
import numpy as np
import math

# A.

In [2]:
a = np.matrix([[1],
               [2],
               [3]])

b = np.matrix([[4],
               [5],
               [6]])

c = np.matrix([[-1],
               [ 1],
               [ 3]])


## other definitions

i = np.matrix([[1],
               [0],
               [0]])
j = np.matrix([[0],
               [1],
               [0]])
k = np.matrix([[0],
               [0],
               [1]])

print(f'a:\n{a}')
print(f'b:\n{b}')
print(f'c:\n{c}')

a:
[[1]
 [2]
 [3]]
b:
[[4]
 [5]
 [6]]
c:
[[-1]
 [ 1]
 [ 3]]


####1. ${2a-b}$

In [3]:
2*a - b

matrix([[-2],
        [-1],
        [ 0]])

####2. $\hat{a}$

In [4]:
def mag(array):
    sum_squared = np.sum(np.square(array))
    magnitude = np.sqrt(sum_squared)
    return magnitude

def unit(array):
    u = array * (1/mag(array))
    return u
    
unit(a)

matrix([[0.26726124],
        [0.53452248],
        [0.80178373]])

####3. $||a||$ and angle of $a$ with respect to $x$-axis

In [5]:
def dot(v1, v2):
    v1 = v1 if v1.shape[0] == 1 else v1.reshape(1,-1) # column to row
    v2 = v2 if v2.shape[1] == 1 else v2.reshape(-1,1) # row to column
    dot_product = (v1*v2).item()
    return dot_product

def cos_theta(v1,v2):
    dot_product = dot(v1,v2)
    denominator = mag(v1)*mag(v2)
    return dot_product/denominator

def angle_between(v1,v2):
    cosine_theta = cos_theta(v1,v2)
    radians = round(np.arccos(cosine_theta),3)
    return radians

def to_degrees(angle):
    degrees = 180*angle/(np.pi)
    degrees = degrees % 360
    return round(degrees, 3)

radians = angle_between(a,i)
print(f'Angle between a and x-axis is {radians} in radians and {to_degrees(radians)} in degrees.')

Angle between a and x-axis is 1.3 in radians and 74.485 in degrees.


####4. direction cosines:  $\theta_\hat{i}$, $\theta_\hat{j}$, $\theta_\hat{k}$, 

In [6]:
theta_i = angle_between(a,i)
theta_j = angle_between(a,j)
theta_k = angle_between(a,k)

print(f'theta_i: {theta_i} radians,'.ljust(25) + f'{to_degrees(theta_i)} degrees')
print(f'theta_j: {theta_j} radians,'.ljust(25) + f'{to_degrees(theta_j)} degrees')
print(f'theta_k: {theta_k} radians,'.ljust(25) + f'{to_degrees(theta_k)} degrees')


theta_i: 1.3 radians,    74.485 degrees
theta_j: 1.007 radians,  57.697 degrees
theta_k: 0.641 radians,  36.727 degrees


####5. angle between $a$ and $b$

In [7]:
radians = angle_between(a,b)
print(f'{radians} radians, {to_degrees(radians)} degrees')

0.226 radians, 12.949 degrees


####6. $a\cdot b$ and $b\cdot a$

In [8]:
a_dot_b = dot(a,b)
b_dot_a = dot(b,a)

print(f'a dot b: {a_dot_b}')
print(f'b dot a: {b_dot_a}')

a dot b: 32
b dot a: 32


####7. $a \cdot b$ using the angle between a and b

In [9]:
a_dot_b_2 = mag(a) * mag(b) * cos_theta(a,b)
print(f'a dot b: {a_dot_b_2}')

a dot b: 32.0


####8. scalar projection of $b$ onto $a$

In [10]:
def scalar_project_v1_onto_v2(v1,v2):
    return round(mag(v1) * cos_theta(v1,v2),3)

project_b_onto_a = scalar_project_v1_onto_v2(b,a)
print(f'{project_b_onto_a} radians,  {to_degrees(project_b_onto_a)} degrees')

8.552 radians,  129.994 degrees


####9. Vector which is perpendicular to $a$

In [11]:
def cross_product(a,b):
    a = np.array(a) if a.shape[0] == 1 else np.array(a.reshape(-1))
    b = np.array(b) if b.shape[0] == 1 else np.array(b.reshape(-1))

    [a1,a2,a3] = a[0]
    [b1,b2,b3] = b[0]

    size_a = a.shape[0]*a.shape[1]
    size_b = b.shape[0]*b.shape[1]

    assert size_a == size_b
    if size_a == 2:
        ret = a1*b2 - a2*b1
    elif size_a == 3:
        ret = i*(a2*b3-a3*b2) - j*(a1*b3-a3*b1) + k*(a1*b2-a2*b1)
    return ret

print(f'One such vector is the cross product of a and b:\n {cross_product(a,b)}')

One such vector is the cross product of a and b:
 [[-3]
 [ 6]
 [-3]]


####10. $a \times b$ and $b \times a$

In [12]:
print(f'a x b:\n{cross_product(a,b)}\n\nb x a:\n{cross_product(b,a)}')

a x b:
[[-3]
 [ 6]
 [-3]]

b x a:
[[ 3]
 [-6]
 [ 3]]


####11. A vector which is perpendicular to both $a$ and $b$

In [13]:
# The cross product of two vectors is perpendicular to both original vectors
# You can confirm that two vectors are perpendicular if their dot product is 0

assert dot(a, cross_product(a,b)) == 0
assert dot(b, cross_product(a,b)) == 0
assert dot(a, cross_product(b,a)) == 0
assert dot(b, cross_product(b,a)) == 0

print('Both axb and bxa are perpendicular to both a and b, by definition of cross products.')

Both axb and bxa are perpendicular to both a and b, by definition of cross products.


####12. The linear dependency between a, b, and c

In [14]:
import sympy


M = np.zeros((3,3))
M[:,0] = np.array(a.reshape(1,-1))
M[:,1] = np.array(b.reshape(1,-1))
M[:,2] = np.array(c.reshape(1,-1))

M = sympy.Matrix(M)

print('reduced row echelon form of matrix with columns a, b, c:\n')
display(M.rref()[0])
print(f'\nlinearly dependent rows: {M.rref()[1]}')
print()
print('The above matrix shows that vectors a, b, and c have the following relationship:')
print('-3a + b + c = 0')

reduced row echelon form of matrix with columns a, b, c:



Matrix([
[1, 0,  3.0],
[0, 1, -1.0],
[0, 0,    0]])


linearly dependent rows: (0, 1)

The above matrix shows that vectors a, b, and c have the following relationship:
-3a + b + c = 0


####13. $a^Tb$ and $b^Ta$

In [15]:
def aTb(a,b):
    assert a.shape == b.shape
    aT = a.reshape(1,-1) if a.shape[0] > 1 else a
    aT = np.array(aT)
    b  = b.reshape(-1,1) if b.shape[1] > 1 else b
    return aT*b

def abT(a,b):
    assert a.shape == b.shape
    bT = b.reshape(1,-1) if b.shape[0] > 1 else b
    bT = np.array(bT)
    a  = b.reshape(-1,1) if a.shape[1] > 1 else a
    return a*bT

print(f'a*Tb:\n{aTb(a,b)}\n')
print(f'a*bT:\n{abT(a,b)}')

a*Tb:
[[32]]

a*bT:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


#B.

In [16]:
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])
d = np.array([[1],[2],[3]])

print('A:\n', A)
print('B:\n', B)
print('C:\n', C)
print('d:\n', d)

A:
 [[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]
B:
 [[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
C:
 [[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]
d:
 [[1]
 [2]
 [3]]


####1. $2A - B$

In [17]:
2*A - B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

####2. $AB$ and $BA$

In [18]:
AB, BA = np.matmul(A,B), np.matmul(B,A)

print(f'AB:\n{AB}')
print(f'BA:\n{BA}')

AB:
[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
BA:
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


####3. $(AB)^T$ and $B^TA^T$

In [19]:
AB_T = np.transpose(AB)
B_T_A_T = np.matmul(np.transpose(B), np.transpose(A))
print(f'(AB).T:\n{AB_T}\n')
print(f'(B.T * A.T):\n{B_T_A_T}')

(AB).T:
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]

(B.T * A.T):
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


####4. $|A|$ and $|C|$

In [20]:
def det_3(M):
    a1, a2, a3 = M[0,0].item(), M[0,1].item(), M[0,2].item()
    b1, b2, b3 = M[1,0].item(), M[1,1].item(), M[1,2].item()
    c1, c2, c3 = M[2,0].item(), M[2,1].item(), M[2,2].item()
    term1 = a1*(b2*c3 - b3*c2)
    term2 = a2*(b1*c3 - b3*c1)
    term3 = a3*(b1*c2 - b2*c1)
    return term1 - term2 + term3


print(f"|A|: {det_3(A)}")
print(f"|C|: {det_3(C)}")

|A|: 55
|C|: 0


####5. The matrix ($A$, $B$, or $C$) in which the row vectors form an orthogonal set

In [21]:
A1, A2, A3 = A[0,:], A[1,:], A[2,:]
B1, B2, B3 = B[0,:], B[1,:], B[2,:]
C1, C2, C3 = C[0,:], C[1,:], C[2,:]

A_orth = np.dot(A1, A2) == 0 and np.dot(A1, A3) == 0 and np.dot(A2, A3) == 0
B_orth = np.dot(B1, B2) == 0 and np.dot(B1, B3) == 0 and np.dot(B2, B3) == 0
C_orth = np.dot(C1, C2) == 0 and np.dot(C1, C3) == 0 and np.dot(C2, C3) == 0

print(f'A\'s rows form an orthogonal set: {A_orth}')
print(f'B\'s rows form an orthogonal set: {B_orth}')
print(f'C\'s rows form an orthogonal set: {C_orth}')

A's rows form an orthogonal set: False
B's rows form an orthogonal set: True
C's rows form an orthogonal set: False


####6. $A^{-1}$ and $B^{-1}$

In [22]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

print(f'A_inv:\n{A_inv}')
print(f'B_inv:\n{B_inv}')

A_inv:
[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
B_inv:
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


####7. $C^{-1}$

In [23]:
try:
    C_inv = np.linalg.inv(C)
    print(f'C_inv:\n{C_inv}')
except:
    print('C_inv is undefined')

C_inv is undefined


####8. $Ad$

In [24]:
np.matmul(A,d)

array([[14],
       [ 9],
       [ 7]])

####9. Scalar projection of rows of $A$ onto vector $d$ with normalizing $d$


In [25]:
row1_proj = scalar_project_v1_onto_v2(np.matrix(A1),np.matrix(d))
row2_proj = scalar_project_v1_onto_v2(np.matrix(A2),np.matrix(d))
row3_proj = scalar_project_v1_onto_v2(np.matrix(A3),np.matrix(d))

print(f'row 1 projection:\n{row1_proj}')
print(f'row 2 projection:\n{row2_proj}')
print(f'row 3 projection:\n{row3_proj}')

row 1 projection:
3.742
row 2 projection:
2.405
row 3 projection:
1.871


####10. Vector projection of rows of $A$ onto vector $d$ without normalizing $d$


In [26]:
def vector_project_v1_onto_v2(v1,v2):
    scalar_projection = scalar_project_v1_onto_v2(v1,v2)
    unit_vector = unit(v2)
    vector_projection = np.round(unit_vector*scalar_projection,3)
    return vector_projection

In [27]:
proj_d_a1 = vector_project_v1_onto_v2(np.matrix(A1), np.matrix(d))
proj_d_a2 = vector_project_v1_onto_v2(np.matrix(A2), np.matrix(d))
proj_d_a3 = vector_project_v1_onto_v2(np.matrix(A3), np.matrix(d))

print(f'proj_d_a1:\n{proj_d_a1}\n')
print(f'proj_d_a2:\n{proj_d_a2}\n')
print(f'proj_d_a3:\n{proj_d_a3}\n')

proj_d_a1:
[[1.]
 [2.]
 [3.]]

proj_d_a2:
[[0.643]
 [1.286]
 [1.928]]

proj_d_a3:
[[0.5]
 [1. ]
 [1.5]]



####11. Linear combination of columns of $A$ using the elements of $d$

In [28]:
(A[:,0]*d[0].item() + A[:,1]*d[1].item() + A[:,2]*d[2].item()).reshape(-1,1)

array([[14],
       [ 9],
       [ 7]])

####12. Solution $x$ for $Bx = d$


In [29]:
def solve_(M,v):
    M_inv = np.linalg.inv(M)
    M1, M2, M3 = M_inv[:,0], M_inv[:,1], M_inv[:,2]
    v1, v2, v3 = v[0], v[1], v[2]
    return np.round(M1*v1 + M2*v2 + M3*v3).reshape(-1,1)

solve_(B,d)

array([[ 1.],
       [ 0.],
       [-0.]])

####13. Solution $x$ for $Cx = d$ and the reason for it


In [30]:
print('There is no solution for Cx = d because C is not invertible. We can check this by confirming that the determinant of C is 0:')
print(det_3(C))

There is no solution for Cx = d because C is not invertible. We can check this by confirming that the determinant of C is 0:
0


# C.

In [31]:
D = np.matrix([[1,2],[3,2]])
E = np.matrix([[2,-2],[-2,5]])
F = np.matrix([[1,2],[2,4]])
print(f'D:\n{D}\n')
print(f'E:\n{E}\n')
print(f'F:\n{F}')

D:
[[1 2]
 [3 2]]

E:
[[ 2 -2]
 [-2  5]]

F:
[[1 2]
 [2 4]]


####1. Eigenvalues and eigenvectors of $D$

In [32]:
import sympy
from sympy import symbols

def eigenvalues_2(M):
    a,b,c,d = M[0,0].item(), M[0,1].item(), M[1,0].item(), M[1,1].item()
    v1,v2,L = sympy.symbols('v1 v2 L')

    exp1 = v1*(a-L) + v2*b
    v1 = sympy.solve(exp1, v1)[0]

    exp2 = v1*c + v2*(d-L)
    L = sympy.solve(exp2, L)

    Ls = np.array(L, dtype=float)
    return Ls[0], Ls[1]

def eigenvectors(M,L):
    M_minus_lambda = M - np.identity(M.shape[0])*L
    v1,v2= sympy.symbols('v1,v2')
    exp = (M_minus_lambda * np.matrix([[v1],[v2]]))[0].item()
    v1 = sympy.solve(exp,v1)[0]
    return np.matrix([round(v1/v2,4), round(v2/v2,4)], dtype=float).reshape(-1,1)


####1. Eigenvalues and corresponding eigenvectors of $D$

In [33]:

L1_d, L2_d = eigenvalues_2(D)
v1_d, v2_d  = eigenvectors(D,L1_d),eigenvectors(D,L2_d)

print(f'Eigenvalue 1: {L1_d}')
print(f'Eigenvector 1:\n{v1_d}')
print(f'\nEigenvalue 2: {L2_d}')
print(f'Eigenvector 2:\n{v2_d}')

Eigenvalue 1: -1.0
Eigenvector 1:
[[-1.]
 [ 1.]]

Eigenvalue 2: 4.0
Eigenvector 2:
[[0.66670227]
 [1.        ]]


####2. Dot product between eigenvectors of $D$

In [34]:
dot(v1_d, v2_d)

0.3332977294921875

####3. Dot product between eigenvectors of $E$

In [35]:
L1_e, L2_e = eigenvalues_2(E)
v1_e, v2_e  = eigenvectors(E,L1_e),eigenvectors(E,L2_e)

dot(v1_e, v2_e)

0.0

####4. Property of eigenvectors of $E$ and its reason

In [36]:
print(f'The matrix E is symmetric, which indicates that its eigenvecotrs are orthogonal.\n\nE:\n{E}')

The matrix E is symmetric, which indicates that its eigenvecotrs are orthogonal.

E:
[[ 2 -2]
 [-2  5]]


####5. Value of a trivial solution $x$ to the equation $Fx = 0$

In [37]:
print('The trivial solution is x [[0],[0]]. We can prove this by showing that F * [[0],[0]] is equal to [[0],[0]].')
print('\nF*x:')
np.matmul(F,np.matrix([[0],[0]],dtype=float))

The trivial solution is x [[0],[0]]. We can prove this by showing that F * [[0],[0]] is equal to [[0],[0]].

F*x:


matrix([[0.],
        [0.]])

####6. Value of two non-trivial solutions $x$ to the equation $Fx = 0$

In [38]:
def row_dot_vars(row,v1,v2):
    row  = row.reshape(1,-1)
    return dot(v1,v2)

print('This can be accomplished by finding eigenvectors of F.\n')
L1_f,  L2_f = eigenvalues_2(F)
vs1_f, vs2_f = eigenvectors(F,L1_f), eigenvectors(F,L2_f)
print(f'Eigenvector 1 is a multiple of:\n{vs1_f}')
print(f'Eigenvector 2 is a multiple of:\n{vs2_f}')

This can be accomplished by finding eigenvectors of F.

Eigenvector 1 is a multiple of:
[[-2.]
 [ 1.]]
Eigenvector 2 is a multiple of:
[[0.5]
 [1. ]]


####7. The only solution $x$ to the equation $Dx = 0$ and the reason for having a single solution

In [39]:
full_rank = np.linalg.matrix_rank(D) == D.shape[0] and np.linalg.matrix_rank(D) == D.shape[1]
if full_rank:
    print('Dx = 0 has a unique solution because D is a full-rank matrix.')

print('If ([[0],[0]] is a solution to Dx = 0, multiplying D by this vector should give ([[0],[0]):')
print(D*np.matrix([[0],[0]]))

Dx = 0 has a unique solution because D is a full-rank matrix.
If ([[0],[0]] is a solution to Dx = 0, multiplying D by this vector should give ([[0],[0]):
[[0]
 [0]]


# D.

$f(x)=x^2+3$<br>
$g(x)=x^2$<br>
$q(x,y)=x^2+y^2$

####1. 1st and 2nd derivatives of $f(x)$ with respect to $x$

In [40]:
#Chain Rule
x,y = symbols(('x','y'))
f = x**2
df = f.diff(x)
ddf = df.diff(x)
print('f(x) = x**2')
print(f'1st derivative: {df}')
print(f'2nd derivative: {ddf}')

f(x) = x**2
1st derivative: 2*x
2nd derivative: 2


####2. Partial derivatives: $\frac{\partial q}{\partial x}$, $\frac{\partial q}{\partial y}$

In [41]:
q = x**2 + y**2
dq_dx = q.diff(x)
dq_dy = q.diff(y)
print('q(x) = x**2 + y**2')
print(f'dq_dx = {dq_dx}')
print(f'dq_dy = {dq_dy}')

q(x) = x**2 + y**2
dq_dx = 2*x
dq_dy = 2*y


####3. $\nabla q(x,y)$

In [42]:
from sympy.vector import gradient, CoordSys3D

R = CoordSys3D(' ')
q = R.x**2 + R.y**2

print('gradient:')
display(gradient(q))

gradient:


2* .x* .i + 2* .y* .j

####4. $\frac{d}{dx} f(g(x))$

In [43]:
## With chain rule
g = symbols('g')
f = g**2 + 3
df_dg = f.diff(g).subs(g,x**2)
g = x**2
dg_dx = g.diff(x)
chain_rule_result = df_dg*dg_dx

## Without chain rule
del f, g
g = x**2
f = g**2 + 3
no_chain_rule_result = f.diff(x)

print('Using chain rule:')
display(chain_rule_result)
print('Without chain rule:')
display(no_chain_rule_result)

Using chain rule:


4*x**3

Without chain rule:


4*x**3